apiVersion: apps/v1
kind: Deployment
metadata:
  name: heroes-api
  labels:
    app: heroes-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heroes-api
  template:
    metadata:
      labels:
        app: heroes-api
    spec:
      containers:
      - name: heroes-api
        image: jandernery/nestjs-api-heroes:1.0
        imagePullPolicy: IfNotPresent
        # image: jandernery/api-marvel:1.4
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        ports:
        - containerPort: 4400
          name: heroes-api
        env:
        - name: PORT_SERVER
          value: "4400"
        - name: DATABASE_URL
          value: "postgresql://heroes:heroes@heroes-postgres-svs:5432/heroes"
---
apiVersion: v1
kind: Service
metadata:
  name: heroes-api
  labels:
    app: heroes-api
spec:
  ports:
    - port: 4400
      targetPort: 4400
  selector:
    app: heroes-api
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  name: heroes-postgres-svs
  labels:
    app: heroes-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: "TCP"
  selector:
    app: heroes-postgres
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: heroes-postgres
  labels:
    app: heroes-postgres
spec:
  serviceName: heroes-postgres
  replicas: 1
  selector:
    matchLabels:
      app: heroes-postgres
  template:
    metadata:
      labels:
        app: heroes-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
          name: postgres
        resources:
          requests:
            cpu: "250m"      # Aumentar a quantidade mínima de CPU
            memory: "512Mi"  # Aumentar a quantidade mínima de memória
          limits:
            cpu: "1000m"      # Aumentar o limite máximo de CPU
            memory: "1Gi"  # Aumentar o limite máximo de memória
        env:
        - name: POSTGRES_USER
          value: heroes
        - name: POSTGRES_PASSWORD
          value: heroes
        - name: POSTGRES_DB
          value: heroes
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
      storageClassName: "standard"

