apiVersion: v1
kind: Service
metadata:
  name: heroes-postgres-svs
  labels:
    app: heroes-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: "TCP"
  selector:
    app: heroes-postgres
  type: ClusterIP